apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: apps
  source:
    repoURL: https://github.com/jhaynie/argocd-test.git
    targetRevision: HEAD
    path: argo/applicationset.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}
